### ISSUE TITLE
'npm start' is missing from package.json

### ISSUE THREAD

**Issue by frostyandy2k** [FraunhoferIAO/awc-core#1]
Readme instructions not working due to missing 'npm start' from package.json

Greetings from KIT TECO

**Comment by dnlzglr** [comment]
I guess you refer to the "How to try it..." instructions. Please note that step 3 changes to the `example` directory (small typo will be fixed). This directory contains a separate package.json that defines the [`start` script](example/package.json#L12).

I hope that fixes your problems?

**Comment by dnlzglr** [comment]
I guess no answer means no problem :wink:

**Comment by frostyandy2k** [comment]
Ups sorry for the late reply. Thanks a lot for clarifying and replying so fast. We’re exploring the framework to see if we can do application composition in our own project.

We’ll post updates on our progress and might open up some more issues :)
